### ISSUE TITLE
[Packaging] python-namespaces renamed to python-maps

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/commons#154]
python-namespaces [0] library is deprecated in favor of python-maps [1],  Please package it as it is required by the "develop" branch

[0]: https://github.com/pcattori/namespaces
[1]: https://github.com/pcattori/maps

**Comment by r0h4n** [comment]
@TimothyAsir @nthomas-redhat any updates?

**Comment by r0h4n** [comment]
@TimothyAsir @nthomas-redhat any updates?

**Comment by mbukatov** [comment]
This seems to be done in commit 0f2b9c6fedd20669f1abd7dc77df79a5b92d1b61 in `develop` branch.
