### ISSUE TITLE
Exception message class for format and handle exceptions 

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/commons#168]
Message framework needs an exception message class for handle and format the exception. the exception message class is the subclass of message class, and it should able to create exception message object with well formatted traceback information.

**Comment by r0h4n** [comment]
Any updates @GowthamShanmugam

**Comment by GowthamShanmugam** [comment]
@r0h4n no rohan patch is ready to merge

**Comment by r0h4n** [comment]
Please send the PR on develop branch @GowthamShanmugam

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/commons/pull/259

**Comment by GowthamShanmugam** [comment]
we can close this
