### ISSUE TITLE
PEP8 check fails

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/commons#177]
[PEP8 code style](https://www.python.org/dev/peps/pep-0008/) is not followed which makes `pep8` check fail during unit test execution, see [latest report from Travis CI](https://travis-ci.org/Tendrl/commons/jobs/206963318).

There are few serious issues among errors, such as:

```
tendrl/commons/message.py:50:28: F821 undefined name 'tendrl_ns'
            self.node_id = tendrl_ns.node_context.node_id
```

Note: to run pep8 check yourself locally, run `tox -e pep8` in current master branch, the environment and the check would be the same as run by Travis CI.

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/commons/commit/9a8fe461af3c3b8d9afaecce0f00469bab8c733d
