### ISSUE TITLE
Unit tests fail for py26 enviroment because of gevent dependency

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/commons#179]
Test environment `py26` of unit test fails with the following error:

```
Collecting gevent>=1.0 (from tendrl-commons==1.2.1)
  Downloading gevent-1.2.1.tar.gz (2.8MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-A756VU/gevent/setup.py", line 39, in <module>
        raise Exception("Please install gevent 1.1 for Python 2.6")
    Exception: Please install gevent 1.1 for Python 2.6
```

See [full log in Travis CI job](https://travis-ci.org/Tendrl/commons/jobs/206888064).

We run unit tests in py26 test environment to check if tendrl-commons would work on CentOS 6.

Gevent rpm package is not part of CentOS 6 distribution, but it is part of EPEL 6 repository (which contains gevent 0.13.8-3.el6). See [python-gevent report from fedoraproject.org](https://apps.fedoraproject.org/packages/python-gevent).

This means that we need to decide which version we will use on CentOS 6 - either 0.13.8-3.el6 from EPEL 6 or maintain different version ourselves (as right now, the minimal version of gevent we require is 1.0 - as specified in install_requires in setup.py). When we figure out which version we will use on CentOS 6, we would just specify this version in configuration of our test environment like this:

```
$ git diff
diff --git a/tox.ini b/tox.ini
index 75187a1..8214098 100644
--- a/tox.ini
+++ b/tox.ini
@@ -20,6 +20,7 @@ deps =
     mock
     coverage
     pytest-cov
+    py26: gevent==0.13.8
     cover: codecov
 commands =
     python -m pytest --ignore=tendrl/commons/tests/fixme --cov=tendrl tendrl/commons/tests
```

So that when py26 test run is executed, correct version of gevent will be installed into test environment.

**Comment by mbukatov** [comment]
This issue is related to https://github.com/Tendrl/commons/issues/159

**Comment by r0h4n** [comment]
Parking this for now, Tendrl will not support py26 fully, PRs welcome to add PY26 support
