### ISSUE TITLE
Unit tests fail for py27 enviroment because of importing non existing modules

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/commons#180]
Two tests from py27 test run fails:

```
tendrl/commons/tests/test_base_flow.py::TestBaseFlow::test_run ERROR
tendrl/commons/tests/test_base_flow.py::TestBaseFlow::test_extract_atom_details ERROR
```

Errors collected by pytest show importing modules which doesn't exist, eg:

```
ImportError while importing test module '/home/travis/build/Tendrl/commons/tendrl/commons/tests/test_commons.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tendrl/commons/tests/test_commons.py:12: in <module>
    from tendrl.commons.etcdobj import etcdobj
E   ImportError: cannot import name etcdobj
```

See [full log from Travis CI](https://travis-ci.org/Tendrl/commons/jobs/206888065).

**Comment by rishubhjain** [comment]
@r0h4n @mbukatov  I guess this issue is resolved and must be closed, If there is something left then I would like to contribute.

**Comment by mbukatov** [comment]
@rishubhjain @r0h4n I rechecked the state of unit tests and noticed that there are no unit tests in `tendrl-commons`. So yes, this issue is no longer valid.

**Comment by rishubhjain** [comment]
Great, we can close the issue :)

**Comment by r0h4n** [comment]
@rishubhjain Your PR provides unit tests, I have linked this issue to the PR

@mbukatov please review https://github.com/Tendrl/commons/pull/433

**Comment by rishubhjain** [comment]
There is already an issue raised for unit tests for which I guess https://github.com/Tendrl/commons/pull/433 will be valid for (https://github.com/Tendrl/commons/issues/85) .
@r0h4n Is there a need to keep this issue alive for the same PR?. I feel this issue is bit out of topic w.r.t to PR

**Comment by mbukatov** [comment]
@rishubhjain your comment about your pull request being off topic seems valid to me, but it's for @r0h4n to settle this in the end - if he thinks that shifting the scope of this issue be to more general based just on the title is better with respect to the issue management, I don't mind

**Comment by r0h4n** [comment]
@rishubhjain lets use this to track the unit tests PR, we dont want to spend a lot of time duplicating bug reports

**Comment by rishubhjain** [comment]
@r0h4n cool, will continue with this

**Comment by rishubhjain** [comment]
@r0h4n at this line https://github.com/Tendrl/commons/blob/develop/tendrl/commons/objects/__init__.py#L323 BaseObject class is called and dict argument is passed, but the class BaseObject is not handling the argument and I feel it will be of no use to pass arguments, and this https://github.com/Tendrl/commons/blob/develop/tendrl/commons/objects/__init__.py#L198 will give error

**Comment by rishubhjain** [comment]
@r0h4n https://github.com/Tendrl/commons/blob/develop/tendrl/commons/message.py#L43 at this line is it mandatory to send message time stamp of message with the message id? I feel there must be an additional check for message time stamp as well

**Comment by r0h4n** [comment]
Coverage is now >90% , we can now close this issue

Fixed: https://github.com/Tendrl/commons/pull/559
