### ISSUE TITLE
Unit tests fail for py34 enviroment because of importing ansible modules

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/commons#181]
Tests from py34 test run fails because of importing ansible modules, eg:

```
____________ ERROR collecting tendrl/commons/tests/test_command.py _____________
ImportError while importing test module '/home/travis/build/Tendrl/commons/tendrl/commons/tests/test_command.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tendrl/commons/tests/test_command.py:9: in <module>
    from tendrl.commons.utils import cmd_utils
tendrl/commons/utils/cmd_utils.py:4: in <module>
    from ansible_module_runner import AnsibleExecutableGenerationFailed
E   ImportError: No module named 'ansible_module_runner'
```

See [full log from Travis CI](https://travis-ci.org/Tendrl/commons/jobs/206888066).

This seems to happen (correct me if I'm wrong) because of [Ansible Python 3 support](https://docs.ansible.com/ansible/python_3_support.html), which has been introduced only recently as a tech preview, and as such is not production ready.

We may consider either dropping py34-cover test run from Travis CI configuration, or skipping test cases which uses ansible modules under the hood [via pytest.mark.skipif](http://doc.pytest.org/en/latest/skipping.html#id1) or [flagging the test cases via xfail](http://doc.pytest.org/en/latest/skipping.html#reason-parameter) when executed with python3 - this depends on how important is for the tendrl code to be python3 compatible.

**Comment by mbukatov** [comment]
If the plan is to move run the project in python3 environment in the future, I would vote for marking ansible test cases with xfail for python3.

**Comment by r0h4n** [comment]
Wont be fully supporting py3, parking this for the short term
