### ISSUE TITLE
investigate desing of configuration processing

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/commons#186]
Multiple tendrl components using tendrl-commons module have the same problem with design of configuration processing, eg:

* https://github.com/Tendrl/node-agent/issues/245
* https://github.com/Tendrl/ceph-integration/issues/146

We should investigate if the problem is not just in all those affected components, but also in tendrl-commons itself.

If the problem turns out to be in tendrl-commons, it would be a serious one as it would be blocking proper unit testing of all other tendrl python components using tendrl-commons.

**Comment by r0h4n** [comment]
This one's not valid anymore since we use a completely different config system now, but we still need to write unit tests
