### ISSUE TITLE
change in invocation of tendrl_ns

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/commons#189]
I'm revieving flake8 reports of tendrl-commons, and I noticed that current implementation which makes tendrl namespace feature available via `tendrl_ns` object which is injected into `__builtin__` module is not friendly to the pep8 check.

This is what flake8 thinks about it:

```
tendrl/commons/jobs/__init__.py:128:20: F821 undefined name 'tendrl_ns'
            flow = tendrl_ns.get_flow(flow_name)
```

At first sight, it looks like some serious error, since it looks as if we were using undefined variable - but in fact it's just usage of tendrl namespace and it's fine. Unfortunately there is no way for flake8 or new contributor reading the code to know that.

Moreover since the `tendrl_ns` object is used many times, this pollutes the pep8 report too much and makes less valuable.

One solution would be to switch off this kind of check in flake8 configuration, but I don't like this as the check is quite useful validation and I would definitely appreciate to have CI to notify us if we did a typo and use undefined variable by mistake.

For this reason, I'm proposing to move this code into a module (eg. `tendrl.commons.tendrl_ns` ), so that it's invocation would be less magic, something like:

```
from tendrl.commons import tendrl_ns

...

flow = tendrl_ns.get_flow(flow_name)
```

This way, the code would be more friendly both to flake8 checker and new contributors.

**Comment by mbukatov** [comment]
Related to https://github.com/Tendrl/commons/issues/177

**Comment by r0h4n** [comment]
1) [flake8] builtins = NS (tox.ini) will help with flake8 issues regarding undefined variable NS

2) Regarding improving readability by "from tendrl.commons import NS", this is a a small but long reaching change and will have to wait till the beta cycle starts

**Comment by mbukatov** [comment]
@r0h4n If the plan is to implement this later when we reach specific milestone, wouldn't be better to keep this open and label it as such?

**Comment by r0h4n** [comment]
Parking this for now
