### ISSUE TITLE
unit tests should check validity of yaml content

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/commons#222]
Unit tests for validation of yaml files included in the project should exists.

This should include:

* yamllint run on all yaml files included in repository
* pytest unit test which will check particular properties of tendrl yaml files
* tendrl code processing those files works (can I read this file and get list of tendrl objects which are defined there?)

Example: fixture would extract all expression which looks like `type: str` and run a simple test on it which will check if type references there is a valid type or not. It would be more interesting for python functions or modules referenced in yaml files.

This issue is blocked by https://github.com/Tendrl/commons/issues/201

**Comment by mbukatov** [comment]
@fbalak (just for your information, this is currently blocked)

**Comment by mbukatov** [comment]
I created this issue based on discussion with @r0h4n this week, for us to not forget out it.

**Comment by r0h4n** [comment]
Now that the yaml files and namespaces are appropriately defined and validated (lacks coverage though)

Tendrl namespaces and yaml file paths:

- https://github.com/Tendrl/commons/tree/develop/tendrl/commons/objects/definition -> (namespace.tendrl) (central store: "_NS/node_agent/compiled_definitions")

- https://github.com/Tendrl/node-agent/tree/develop/tendrl/node_agent/objects/definition -> (namespace.node_agent) (central store: "_NS/node_agent/compiled_definitions")

- https://github.com/Tendrl/node-agent/tree/develop/tendrl/provisioning/objects/definition -> (namespace.provisioning) (central store: "_NS/node_agent/compiled_definitions")

- https://github.com/Tendrl/node-agent/tree/develop/tendrl/integrations/ceph/objects/definition -> (namespace.integrations.ceph) (central store: "_NS/node_agent/compiled_definitions")

- https://github.com/Tendrl/node-agent/tree/develop/tendrl/integrations/gluster/objects/definition -> (namespace.integrations.gluster) (central store: "_NS/node_agent/compiled_definitions")

- https://github.com/Tendrl/gluster-integration/tree/develop/tendrl/gluster_integration/objects/definition -> (namespace.gluster) (central store: "clusters/$cluster_id/_NS/definitions")

- https://github.com/Tendrl/ceph-integration/tree/develop/tendrl/ceph_integration/objects/definition -->
(namespace.ceph) (central store: "clusters/$cluster_id/_NS/definitions")

- https://github.com/Tendrl/performance-monitoring/tree/develop/tendrl/performance_monitoring/objects/definition -->
(namespace.performance_monitoring) (central store: "_NS/performance_monitoring/definitions")
(cc : @anmolbabu )

- https://github.com/Tendrl/performance-monitoring/tree/develop/node_monitoring/tendrl/node_monitoring/objects/definition -->
(namespace.node_monitoring) (central store: "_NS/node_monitoring/definitions")

- https://github.com/Tendrl/alerting/tree/develop/tendrl/alerting/objects/definition -->
(namespace.alerting) (central store: "_NS/alerting/definitions")


Can we start work on this issue?

**Comment by fbalak** [comment]
@r0h4n yes, I will look at it.

**Comment by r0h4n** [comment]
Any progress?

**Comment by r0h4n** [comment]
Will re-open when @fbalak starts working again

**Comment by mbukatov** [comment]
@r0h4n could you open this again for us and @fbalak to not forget about it?

**Comment by mbukatov** [comment]
My notes: if the implementation will include some pytest fixtures, it would be good to make theme available as a python plugins, so that other tendrl python modules would be able to reuse them.

**Comment by rishubhjain** [comment]
@fbalak Hi, I have been working on unit test cases (https://github.com/Tendrl/commons/pull/433) , and if possible I would like to contribute to this particular task as well.Do let me know if I could contribute in any way.

**Comment by r0h4n** [comment]
Parking this for short term since it is not something @Tendrl/tendrl-core  wants to focus on.
