### ISSUE TITLE
Details about EtcdKeyNotFound (eg. which key is actually missing) is not reported

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/commons#224]
Based on the following report of flake8 check:

```
tendrl/commons/objects/__init__.py:59:40: F841 local variable 'ex' is assigned to but never used
        except etcd.EtcdKeyNotFound as ex:
```

I noticed that the error handling code in `tendl.commons.objects.BaseObject` doesn't report which key is actually missing in etcd properly:

```
def save(self):
    try:
        ...
    except etcd.EtcdKeyNotFound as ex:
        cls_etcd = cs_utils.to_etcdobj(self._etcd_cls, self)
```

**Comment by mbukatov** [comment]
Reported based on discussion with @r0h4n who acknowledged that this is a real issue.

**Comment by r0h4n** [comment]
On further look, this is expected behavior for objects which are being saved in etcd for the very first time, hence only logging the message and moving on

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/commons/commit/8ec6c63282c03271e527a818c2b5f4e5f748bc2e
