### ISSUE TITLE
Missing dependency python-ruamel-yaml

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/commons#252]
Please rebuild "python-ruamel-yaml-0.12.14-9.el7" as it is required by commons

**Comment by r0h4n** [comment]
@TimothyAsir any updates?

**Comment by TimothyAsirJeyasing** [comment]
facing few issues during the build. Surely i will fix it and rebuild and will update.

**Comment by nthomas-redhat** [comment]
@r0h4n , can we close this issue?

**Comment by sankarshanmukhopadhyay** [comment]
@nthomas-redhat I'm going to close this as builds are available.
