### ISSUE TITLE
NodeContext is a shared namespace object which gets overwritten with tags with addition of integration module

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/commons#263]
1. NodeContext is a shared Namespace object and not specific to integration module i.e, NS.node_context and not NS.<integration_name>.node_context
2. tags is a field in NodeContext i.e, NS.node_context
3. Each integration module on each node can execute only jobs with a specific set of tags that exactly 
    matches the tags in integration module's conf file. Now this means if node_context has all tags from all 
    modules that is if it is super-set of all tags then the job can't be executed by the integration module. On the other hand, even overwriting the tags would fail other integrations

**Comment by anmolbabu** [comment]
@r0h4n I had no permissions to assign it to you Could you please assign this to yourself...

**Comment by r0h4n** [comment]
Fixed in latest builds
