### ISSUE TITLE
Integration id should not be mandatory parameter for Job

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/commons#269]
Integration id should not be a mandatory parameter for job because:

1. Integration id which is basically cluster id is currently required by commons job framework to be always present.
2. There are integrations like performance-monitoring that can exist even when there's no cluster.

So, integration id should be made optional parameter...

**Comment by anmolbabu** [comment]
@r0h4n I have raised the issue for this...

**Comment by nthomas-redhat** [comment]
Closing the issue as it is already merged
