### ISSUE TITLE
Authorize_key util is not working when selinux is enabled

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/commons#274]
If selinux is disabled then authorize utils is copying key to particular place without any issue, and it is automatically creating .ssh/authorized_keys  file and folder also.
Actual problem is if selinux is enabled it gives error like ValueError('No JSON object could be decoded',).
first case is:
    if .ssh/authorized_keys file is exist then it is copying key successfully but it give error also. 
second case is:
   if .ssh/authorized_keys file not exist when i run first time it creating authorized_keys but file is empty, second time it copying key successfully also raising error. third time no error came.

**Comment by GowthamShanmugam** [comment]
@shtripat @r0h4n

**Comment by GowthamShanmugam** [comment]
@shtripat @r0h4n

**Comment by r0h4n** [comment]
You are not setting the "manage_dir" flag for the ansible module "authorize_key", you will have to set it along with user and key

https://github.com/ansible/ansible-modules-core/blob/devel/system/authorized_key.py#L50

That should help

**Comment by GowthamShanmugam** [comment]
@r0h4n default manage_dir value is true so no need to give this, i ahve tested with this also

**Comment by r0h4n** [comment]
@GowthamShanmugam Please find root cause of failure of ansible authorize_key module, we cannot hack around our way if the ansible module is faulty. We should file bugs on ansible module if it doesnt behave as it should

**Comment by GowthamShanmugam** [comment]
@r0h4n ok

**Comment by r0h4n** [comment]
Is this issue resolved?

**Comment by GowthamShanmugam** [comment]
_@r0h4n @shtripat it is fixed, we can close this issue
