### ISSUE TITLE
Running commons atoms from integrations fails

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/commons#286]
The debug log is as below:

2017-03-22T17:50:52+0000 - /usr/lib/python2.7/site-packages/tendrl/commons/flows/__init__.py - __init__.py:64 -                  run() - INFO - Processing pre-runs for flow: node_monitoring.flows.ConfigureCollectd
2017-03-22T17:50:52+0000 - /usr/lib/python2.7/site-packages/tendrl/commons/flows/__init__.py - __init__.py:76 -                  run() - INFO - Start pre-run : tendrl.objects.Node.atoms.CheckNodeUp
> /usr/lib/python2.7/site-packages/tendrl/commons/flows/__init__.py(140)_execute_atom()
-> try:
(Pdb) l
135  	                          (atom_fqn, self._defs['help'])
136  	                    LOG.info(msg)
137  	
138  	    def _execute_atom(self, atom_fqdn):
139  	        import pdb; pdb.set_trace()
140  ->	        try:
141  	            ns, atom_name = atom_fqdn.split(".atoms.")
142  	            ns, obj_name = ns.split(".objects.")
143  	
144  	            runnable_atom = self._ns.get_atom(obj_name, atom_name)
145  	            try:
(Pdb) n
> /usr/lib/python2.7/site-packages/tendrl/commons/flows/__init__.py(141)_execute_atom()
-> ns, atom_name = atom_fqdn.split(".atoms.")
(Pdb) n
> /usr/lib/python2.7/site-packages/tendrl/commons/flows/__init__.py(142)_execute_atom()
-> ns, obj_name = ns.split(".objects.")
(Pdb) n
> /usr/lib/python2.7/site-packages/tendrl/commons/flows/__init__.py(144)_execute_atom()
-> runnable_atom = self._ns.get_atom(obj_name, atom_name)
(Pdb) ns
'tendrl'
(Pdb) obj_name
'Node'
(Pdb) atom_name
'CheckNodeUp'
(Pdb) s
--Call--
> /usr/lib/python2.7/site-packages/tendrl/commons/__init__.py(113)get_atom()
-> def get_atom(self, obj_name, atom_name):
(Pdb) n
> /usr/lib/python2.7/site-packages/tendrl/commons/__init__.py(114)get_atom()
-> private_name = "_" + obj_name
(Pdb) n
> /usr/lib/python2.7/site-packages/tendrl/commons/__init__.py(115)get_atom()
-> return self.current_ns.objects[private_name]['atoms'][atom_name]
(Pdb) private_name
'_Node'
(Pdb) self.current_ns.objects[private_name]
*** KeyError: '_Node'
(Pdb) self.current_ns
NamedDict({'definitions': <tendrl.node_monitoring.objects.definition.Definition object at 0x24c45d0>, 'ns': <tendrl.node_monitoring.NodeMonitoringNS object at 0x24bc410>, 'config': <tendrl.node_monitoring.objects.config.Config object at 0x2156c10>, 'flows': NamedDict({'ConfigureCollectd': <class 'tendrl.node_monitoring.flows.configure_collectd.ConfigureCollectd'>, 'BaseFlow': <class 'tendrl.commons.flows.BaseFlow'>}), 'objects': NamedDict({'Definition': <class 'tendrl.node_monitoring.objects.definition.Definition'>, '_Config': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), '_Definition': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), 'BaseObject': <class 'tendrl.commons.objects.BaseObject'>, '_BaseObject': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), 'Config': <class 'tendrl.node_monitoring.objects.config.Config'>})})
(Pdb) NS
NamedDict({'config': <tendrl.node_monitoring.objects.config.Config object at 0x2156c10>, 'node_monitoring': NamedDict({'definitions': <tendrl.node_monitoring.objects.definition.Definition object at 0x24c45d0>, 'ns': <tendrl.node_monitoring.NodeMonitoringNS object at 0x24bc410>, 'config': <tendrl.node_monitoring.objects.config.Config object at 0x2156c10>, 'flows': NamedDict({'ConfigureCollectd': <class 'tendrl.node_monitoring.flows.configure_collectd.ConfigureCollectd'>, 'BaseFlow': <class 'tendrl.commons.flows.BaseFlow'>}), 'objects': NamedDict({'Definition': <class 'tendrl.node_monitoring.objects.definition.Definition'>, '_Config': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), '_Definition': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), 'BaseObject': <class 'tendrl.commons.objects.BaseObject'>, '_BaseObject': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), 'Config': <class 'tendrl.node_monitoring.objects.config.Config'>})}), 'etcd_orm': <tendrl.commons.etcdobj.Server object at 0x7f590b364fd0>, 'central_store_thread': <NodeMonitoringEtcdCentralStore at 0x279ef50>, 'publisher_id': 'node_monitoring', 'tendrl': NamedDict({'flows': NamedDict({'ImportCluster': <class 'tendrl.commons.flows.import_cluster.ImportCluster'>, 'SetupSsh': <class 'tendrl.commons.flows.setup_ssh.SetupSsh'>, 'CreateCluster': <class 'tendrl.commons.flows.create_cluster.CreateCluster'>}), 'objects': NamedDict({'_Definition': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), 'Service': <class 'tendrl.commons.objects.service.Service'>, '_Cpu': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), 'Platform': <class 'tendrl.commons.objects.platform.Platform'>, '_Node': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({'BaseAtom': <class 'tendrl.commons.objects.BaseAtom'>, 'CheckNodeUp': <class 'tendrl.commons.objects.node.atoms.check_node_up.CheckNodeUp'>, 'Cmd': <class 'tendrl.commons.objects.node.atoms.cmd.Cmd'>})}), 'Memory': <class 'tendrl.commons.objects.memory.Memory'>, 'Node': <class 'tendrl.commons.objects.node.Node'>, '_NodeContext': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), 'NodeContext': <class 'tendrl.commons.objects.node_context.NodeContext'>, '_DetectedCluster': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), 'Job': <class 'tendrl.commons.objects.job.Job'>, 'TendrlContext': <class 'tendrl.commons.objects.tendrl_context.TendrlContext'>, 'Definition': <class 'tendrl.commons.objects.definition.Definition'>, '_Os': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), 'Package': <class 'tendrl.commons.objects.package.Package'>, '_Platform': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), '_Disk': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), '_Memory': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), '_Job': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), '_Package': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), 'Os': <class 'tendrl.commons.objects.os.Os'>, 'Cpu': <class 'tendrl.commons.objects.cpu.Cpu'>, '_File': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({'BaseAtom': <class 'tendrl.commons.objects.BaseAtom'>, 'Write': <class 'tendrl.commons.objects.file.atoms.write.Write'>})}), '_TendrlContext': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({})}), 'File': <class 'tendrl.commons.objects.file.File'>, 'DetectedCluster': <class 'tendrl.commons.objects.detected_cluster.DetectedCluster'>, 'Disk': <class 'tendrl.commons.objects.disk.Disk'>, '_Service': NamedDict({'flows': NamedDict({}), 'atoms': NamedDict({'BaseAtom': <class 'tendrl.commons.objects.BaseAtom'>, 'CheckServiceStatus': <class 'tendrl.commons.objects.service.atoms.check_service_status.CheckServiceStatus'>})})}), 'definitions': <tendrl.commons.objects.definition.Definition object at 0x2641150>, 'ns': <tendrl.commons.TendrlNS object at 0x26415d0>, 'node_context': <tendrl.commons.objects.node_context.NodeContext object at 0x2872850>, 'tendrl_context': <tendrl.commons.objects.tendrl_context.TendrlContext object at 0x2872510>}), 'type': 'monitoring', 'node_context': <tendrl.commons.objects.node_context.NodeContext object at 0x2872850>, 'tendrl_context': <tendrl.commons.objects.tendrl_context.TendrlContext object at 0x2872510>})

**Comment by anmolbabu** [comment]
@r0h4n Please check this as can be seen NS has _Node while self.current_ns which points to integration namespace(node-monitoring in my case) doesn't have it.

In this case I am trying to run check_node_up atom of commons as a pre-run

**Comment by anmolbabu** [comment]
An attempt to fix this has been made at https://github.com/Tendrl/commons/pull/287

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/commons/pull/288
