### ISSUE TITLE
No way to fetch cluster type

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/commons#298]
The TendrlContext as in https://github.com/Tendrl/commons/blob/develop/tendrl/commons/objects/tendrl_context/__init__.py does not contain sds type.

**Comment by anmolbabu** [comment]
@r0h4n @nthomas-redhat @shtripat

**Comment by r0h4n** [comment]
Please check commit https://github.com/Tendrl/commons/commit/2147759fe8ac974762ffc430f275de4e0f061090

Fixed

**Comment by anmolbabu** [comment]
@r0h4n it still does not have SDS / cluster type
