### ISSUE TITLE
If ceph allows spaces in cluster name

### ISSUE THREAD

**Issue by shtripat** [Tendrl/commons#351]
If not add check in API and tendrl core to not allow spaces in cluster name.

**Comment by anmolsachan** [comment]
This is present in ceph documentation : http://docs.ceph.com/docs/master/install/manual-deployment/  

Cluster Name: Ceph clusters have a cluster name, which is a simple string without spaces. The default cluster name is ceph, but you may specify a different cluster name. Overriding the default cluster name is especially useful when you are working with multiple clusters and you need to clearly understand which cluster your are working with.

**Comment by shtripat** [comment]
With the above definitions, we need to add checks in API layer and in create cluster flow to not allow spaces in cluster name.
