### ISSUE TITLE
[rfe] Base object should provide an exists() method

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/commons#363]
Base object should have a method to check the existence of a particular object. It should return a Boolean value.  Current load method doesn't provide this functionality

**Comment by r0h4n** [comment]
Thanks for adding this, will work on this next week

**Comment by r0h4n** [comment]
Fixed https://github.com/Tendrl/commons/commit/a2772fdb9a5d8b83db4818b0439825ee73bae25d
