### ISSUE TITLE
etcd read/write operations fail for all tendrl modules after few days

### ISSUE THREAD

**Issue by fbalak** [Tendrl/commons#411]
If tendrl modules are running for more days (around 4-5 days) then read/write operations to etcd fail for all tendrl modules.

**Comment by r0h4n** [comment]
Fixed:
https://github.com/Tendrl/commons/commit/520786ffc7b72199383a30dda8f48df0dc666ee7
https://github.com/Tendrl/commons/commit/63d146211f2d0228cf552d8ab248312d1f9522b8
