### ISSUE TITLE
Move to ansible 2.3

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/commons#438]
Investigate and adopt ansible 2.3 instead of depending on ansible 2.2.1

@GowthamShanmugam please make use of ansible 2.3 for running Tendrl scenarios and report failures here (if any)

**Comment by japplewhite** [comment]
I am very interested in the answer here - the gluster team would like to move to ansible 2.3 but I have pushed back due to my perception that it was not possible.

**Comment by r0h4n** [comment]
I sent out a PR for this, Tendrl can now work with ansible <2.2 or >2.2 , closing this one

**Comment by japplewhite** [comment]
@r0h4n do we really need it to work with <2.2? I worry about security and similar issues there..
