### ISSUE TITLE
All tendrl modules fail to start due to python-etcd dependency issue -- dnspython

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/commons#443]
May  7 12:38:58 dhcpxx-xxx tendrl-node-agent: Traceback (most recent call last):
May  7 12:38:58 dhcpxx-xxx tendrl-node-agent: File "/usr/bin/tendrl-node-agent", line 5, in <module>
May  7 12:38:58 dhcpxx-xxx tendrl-node-agent: from pkg_resources import load_entry_point
May  7 12:38:58 dhcpxx-xxx tendrl-node-agent: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3011, in <module>
May  7 12:38:58 dhcpxx-xxx tendrl-node-agent: parse_requirements(__requires__), Environment()
May  7 12:38:58 dhcpxx-xxx tendrl-node-agent: File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
May  7 12:38:58 dhcpxx-xxx tendrl-node-agent: raise DistributionNotFound(req)
May  7 12:38:58 dhcpxx-xxx tendrl-node-agent: pkg_resources.DistributionNotFound: dnspython>=1.13.0

I fixed this issue locally by removing dnspython>=1.13.0 from /usr/lib/python2.7/site-packages/python_etcd-0.4.5-py2.7.egg-info/requires.txt

**Comment by anmolbabu** [comment]
[root@dhcpxx-xxx ~]# rpm -qa|grep tendrl
tendrl-node-monitoring-1.2.3-1.el7.noarch
tendrl-dashboard-1.2.3-05_07_2017_04_11_04.noarch
tendrl-api-1.2.3-05_07_2017_01_51_05.noarch
tendrl-commons-1.2.3-05_07_2017_05_13_23.noarch
tendrl-performance-monitoring-1.2.3-1.el7.noarch
tendrl-node-agent-1.2.3-05_07_2017_00_01_36.noarch
tendrl-api-httpd-1.2.3-05_07_2017_01_51_05.noarch
tendrl-alerting-1.2.3-05_07_2017_05_24_03.noarch

All master branch rpms

**Comment by r0h4n** [comment]
This has been fixed, still reproducible?
