### ISSUE TITLE
ceph map update fails while cluster sync due to exception while calculating hash for the sync object

### ISSUE THREAD

**Issue by shtripat** [Tendrl/commons#454]
While saving the `SyncObject` in `ceph-integration` cluster sync, during calculation of hash of the SyncObject, its throws the exception `TypeError: datetime.datetime(2017, 5, 11, 8, 56, 1, 888246, tzinfo=<UTC>) is not JSON serializable`.

Because of this exception the old state of the `SyncObject` as-is is saved again and this if some additional OSD/MON (s) added to the cluster, they never get reflected in ceph cluster in central store.

**Comment by r0h4n** [comment]
Fixed: please try to reproduce this one
