### ISSUE TITLE
Cluster import is broken

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/commons#463]
Import flows fails to import all the nodes in the cluster. Job is processed only for the node where the parent job is taken. while looking at the child jobs, could see the below error:

{
"key": "/queue/404cd4a9-b2c3-482e-8fa5-99d1e9b5af32/errors",
"value": "TendrlContext.integration_id cannot be an existing integration id.cf21e52b-051e-4b24-bbbf-6eb7484f5b55 already used for a cluster",
"modifiedIndex": 58010,
"createdIndex": 58010
}

By looking at the code I suspect this block is causing the regression:
https://github.com/Tendrl/commons/blob/develop/tendrl/commons/flows/import_cluster/__init__.py#L28

**Comment by r0h4n** [comment]
@nthomas-redhat closing this one, let me know once you test it out
