### ISSUE TITLE
Codecov Error

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/commons#556]
After passing all the test cases Codecov is throwing an "Missing repository upload token" error https://travis-ci.org/Tendrl/commons/jobs/237406338#L304

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/commons/commit/e6756315db4750515be731ab6ea4fc6d2a2a30f1

Report: https://travis-ci.org/Tendrl/commons/jobs/237437297
