### ISSUE TITLE
etcd configuration directives need to be handled differently

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/commons#58]
It should easier and less error prone to have just one `etcd_url` directive in lieu of the current `etcd_port` and `etcd_connection` directives. `etcd_url` should accept http urls, including the port eg. http://localhost:2379.

Furthermore, since the specification of the port is optional in an http url, the value, if not specified, should default to `2379`.

The current implementation brings up issues around the handling of the directives eg. should the `etcd_connection` be specified without a port but `etcd_port` be missing etc. There are a few such permutations that would need to be handled, specifically regarding the population of default values, if the directives are kept separate. All of these can be avoided by using a single directive and assuming a default value of the port to be 2379.

**Comment by mbukatov** [comment]
Is this still valid? My understanding is that tendrl-commons is not processing any config files directly anymore.

On current master (e4a8559), I see only some remnants in unit tests:

```
$ git grep etcd_connection
tendrl/commons/__init__.py:                       'host': self.config.data["etcd_connection"]}
tendrl/commons/tests/test_rpc_job_process.py:            elif parameter == "etcd_connection":
tendrl/commons/tests/test_rpc_job_process.py:            elif parameter == "etcd_connection":
tendrl/commons/tests/test_rpc_job_process.py:            elif parameter == "etcd_connection":
tendrl/commons/tests/test_rpc_job_process.py:            elif parameter == "etcd_connection":
$ git grep etcd_port
tendrl/commons/__init__.py:        etcd_kwargs = {'port': self.config.data['etcd_port'],
tendrl/commons/tests/test_rpc_job_process.py:            if parameter == "etcd_port":
tendrl/commons/tests/test_rpc_job_process.py:            if parameter == "etcd_port":
tendrl/commons/tests/test_rpc_job_process.py:            if parameter == "etcd_port":
tendrl/commons/tests/test_rpc_job_process.py:            if parameter == "etcd_port":
$ git grep etcd_url
$
```
On the other hand, in current develop branch (f886784) the older scheme is used:

```
$ git grep etcd_connection
tendrl/commons/__init__.py:                               "etcd_connection"]}
tendrl/commons/flows/import_cluster/ceph_help.py:                   "etcd_connection": tendrl_ns.config.data['etcd_connection'],
tendrl/commons/flows/import_cluster/gluster_help.py:                   "etcd_connection": tendrl_ns.config.data['etcd_connection'],
tendrl/commons/tests/test_rpc_job_process.py:            elif parameter == "etcd_connection":
$ git grep etcd_port
tendrl/commons/__init__.py:            etcd_kwargs = {'port': self.current_ns.config.data['etcd_port'],
tendrl/commons/flows/import_cluster/ceph_help.py:    config_data = {"etcd_port": tendrl_ns.config.data['etcd_port'],
tendrl/commons/flows/import_cluster/gluster_help.py:    config_data = {"etcd_port": tendrl_ns.config.data['etcd_port'],
tendrl/commons/tests/test_rpc_job_process.py:            if parameter == "etcd_port":
```

Looking for [example config files in other repositories](https://github.com/Tendrl/node-agent/blob/1c1e34e87a7689eb98f5f63c8d2e470098f87aab/etc/tendrl/node-agent/node-agent-dev.conf.yaml) reveals that this idea hasn't been implemented:

```
---
etcd_port: 2379
etcd_connection: 0.0.0.0
```

## Conclusion

Change proposed there (correct me if I'm wrong):

* hasn't been implemented
* is out of scope of tendrl-commons

So if we still plan to implement this, we need to create multiple issues in other repositories and close this one. If we no longer plan to do this, we should close the issue.

**Comment by r0h4n** [comment]
These NS (node_agent, tendrl.integrations.{ceph, gluster}, performance_monitoring, node_monitoring, alerting) provide their own Config objects which are available at "NS.config.data" 

I think the etcd_port and etcd_connection should stay the same
