### ISSUE TITLE
Tendrl BaseObject needs a load_all() 

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/commons#585]
Tendrl BaseObject should provide a load_all() function which loads all instances of the object from central store

- use Object's tendrl definition "value" to extract location where the list of primary keys can be found for that object.

**Comment by r0h4n** [comment]
@rishubhjain please take a look at this issue, ask here if any questions

**Comment by rishubhjain** [comment]
@r0h4n As per my understanding, the already existing load function in BaseObject loads the object of the  class (inheriting BaseObject), and the load_all() function must load all the instances of this class(inheriting BaseObject), am I correct?

**Comment by r0h4n** [comment]
BaseObject.load() function loads that instance of the class from etcd,

BaseObject.load_all() should load all instances of the class from etcd

makes sense?

**Comment by rishubhjain** [comment]
Yes,
The class mentioned here is referring to the class that is inheriting BaseObject Metaclass right?

**Comment by rishubhjain** [comment]
@r0h4n I guess  we can close this issue.
