### ISSUE TITLE
Lock all nodes involved in Create/Import/Expand cluster flows per job

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/commons#594]
- For flows Create/Import/Expand cluster

- At Start of the flow check if participating nodes (Node[]) arent locked by some other job id
- If the nodes are already locked and the locking job_id status is "processing" fail the current flow stating the reason. If the locking job_id is "finished|failed", expire and acquire the lock
- Once confirmed that participating nodes are free, lock them (atomic compare and swap check prevExists=False) using current job id in etcd `/nodes/:node_id/locked_by 
`
- At completion of flow delete `/nodes/:node_id/locked_by`  key

**Comment by brainfunked** [comment]
The locks would need a TTL value.

**Comment by r0h4n** [comment]
@brainfunked What should be an ideal value for TTL? We are talking about locking nodes for the duration of Create, Import, Expand flows which vary highly based on many factors.

I dont think we should have a TTL, rather, we should ensure these locks are expired on success and any failure in said flows

**Comment by brainfunked** [comment]
Agreed about the variable duration.

In lieu of the TTL, it may be better to instead check if the node is locked by a particular job and whether job has been completed. If yes, the stale lock and be expired and a new one acquired in it's place, in the new job.

**Comment by nnDarshan** [comment]
If the node-agent that picked the job(create/import/expand) is stopped while the job is in processing state. The node stays in the locked state indefinitely.
How do we handle that ?

**Comment by r0h4n** [comment]
@nnDarshan Apart from user manually stopping the node-agent, what Tendrl code stops the node-agent?

**Comment by brainfunked** [comment]
It's a possible scenario in a crash. It does need to be handled. That's where the TTL is useful.

In any case, the jobs themselves need to be expire after a certain duration - not more than a few minutes. So how we compute the duration still needs to be figured out.

**Comment by shtripat** [comment]
I have a PR for locking the bricks while volume creation flow at https://github.com/Tendrl/gluster-integration/pull/280.

Locking is something which we should do based on which flow is being executed. If create/import cluster lock the nodes. If volume creation lock the bricks. There could be other such scenarios.

**Comment by nnDarshan** [comment]
@rohan I agree its a corner case, only user has to stop the node-agent service / if node itself goes down

**Comment by r0h4n** [comment]
Lets handle the corner cases once we have the actual code merged. Will keep this issue open to handle corner cases later

**Comment by brainfunked** [comment]
Nah, it's not a corner case. The functionality needs to be designed such that it can address this problem.

**Comment by r0h4n** [comment]
@nnDarshan @GowthamShanmugam have you guys started work on this?
