### ISSUE TITLE
common libraries should not depend upon hardcoded configuration file locations

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/commons#60]
The common codebase needs to behave as a library and not as an application. Since it cannot be used on it's own, and only be used as part of another codebase such as the node agent, all the configuration file samples and configuration file locations should be shipped as part of these applications. The common codebase should provide only the code that can take configurable parameters that point to the correct path of the configuration files.

Tied to https://github.com/Tendrl/common/issues/62.

**Comment by shtripat** [comment]
This would be taken care as part of re-factoring PR #71

**Comment by shtripat** [comment]
I feel this can be closed.
