### ISSUE TITLE
common libraries should not log to their own log files, but instead enable the applications using them to log to theirs

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/commons#62]
Logging configuration and output is the domain of an application such as the node agent or bridges that use common as a library. The common codebase should ship with modules that allow a common logging code to be reused, but common should never require any logging configuration or file by itself.  The applications should ship with sample configuration files custom tuned for each application. The common code should allow these configuration files and the actual logging to be used appropriately in the applications, without having to be re-implemented.

Tied to https://github.com/Tendrl/common/issues/60.

**Comment by mbukatov** [comment]
What is the current status here? Is development work finished or are there some details which still needs to be addressed? When I check tendrl managed storage done (machine running tendrl-node-agent and integration services), I don't see any log for tendrl-commons itself.
