### ISSUE TITLE
Create Cluster flow should wait till cluster.sync_status is done

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/commons#642]
After creating a cluster, tendrl should wait for the import of the newly created cluster to happen. 

When /clusters/:integration_id/sync_status is "done", only then CreateCluster job should be marked as "finished"

Depends on: https://github.com/Tendrl/commons/issues/641

**Comment by shtripat** [comment]
@r0h4n who sets the value of sync_status = done while import?

**Comment by r0h4n** [comment]
@shtripat https://github.com/Tendrl/ceph-integration/blob/develop/tendrl/ceph_integration/sds_sync/__init__.py#L141
