### ISSUE TITLE
Node locking logic have some problem

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/commons#643]
During create cluster or import cluster or expand cluster flow node-agent is locking set of nodes. This logic have some problem like if node ids are wrong it is creating some new node entries under /nodes with locked by attribute. And one more problem is if set of nodes ids are already locked by some flow then it gives error message for first node only.

**Comment by GowthamShanmugam** [comment]
@r0h4n @shtripat

**Comment by r0h4n** [comment]
@GowthamShanmugam The "gives error message for first node only" is ok 

As for the other issues of wrong node id's , please send a PR

**Comment by GowthamShanmugam** [comment]
@r0h4n ok
