### ISSUE TITLE
The load_all() function returns None

### ISSUE THREAD

**Issue by shtripat** [Tendrl/commons#655]
While trying to load all the volumes as below

```
volumes = NS.gluster.objects.Volume().load_all()
```

it returns `None`. It should return all the volumes for the current cluster correctly.

**Comment by r0h4n** [comment]
The fix linked to this bug looks like a hack, can we discuss a better approach here?

**Comment by r0h4n** [comment]
@shtripat @rishubhjain updates?

**Comment by rishubhjain** [comment]
I am debugging the issue and trying to find a solution, but for now I don't have a better solution. Will try to find a better approach as soon as possible

**Comment by r0h4n** [comment]
@rishubhjain whats the update on this? I see a PR from @shtripat

**Comment by rishubhjain** [comment]
@r0h4n I don't have a better solution for now. I am working on Monitoring-Integration. Will it be ok if I could work on this after completing monitoring-integration task?
