### ISSUE TITLE
Unit tests are failing

### ISSUE THREAD

**Issue by fbalak** [Tendrl/commons#681]
There are unit tests that fail. These should be fixed:

- [ ] test_list_modules_in_package_path FAILED
- [ ] test_run <- /usr/lib/python2.7/site-packages/tendrl/commons/tests/flows/test_flows_init.py FAILED
- [ ] test_create_cluster <- /usr/lib/python2.7/site-packages/tendrl/commons/tests/flows/create_cluster/test_cc_init.py FAILED
- [ ] test_install_python_gdeploy <- /usr/lib/python2.7/site-packages/tendrl/commons/tests/flows/create_cluster/test_cc_utils.py FAILED
- [ ] test_expand_cluster <- /usr/lib/python2.7/site-packages/tendrl/commons/tests/flows/expand_cluster/test_ec_ceph_help.py FAILED
- [ ] test_existing_mons <- /usr/lib/python2.7/site-packages/tendrl/commons/tests/flows/expand_cluster/test_ec_ceph_help.py FAILED
- [ ] test_import_ceph <- /usr/lib/python2.7/site-packages/tendrl/commons/tests/flows/import_cluster/test_ceph_help.py FAILED
- [ ] test_run <- /usr/lib/python2.7/site-packages/tendrl/commons/tests/flows/import_cluster/test_import_cluster_init.py FAILED
- [ ] test_save FAILED
- [ ] test_constructor FAILED
- [ ] test_get_node_id <- /usr/lib/python2.7/site-packages/tendrl/commons/tests/objects/node_context/test_node_context_init.py FAILED
- [ ] test_run <- /usr/lib/python2.7/site-packages/tendrl/commons/tests/objects/service/atoms/check_service_status/test_check_service_status_init.py FAILED

### How to check:
```
$ tox -e py27
```

**Comment by r0h4n** [comment]
WontFix anytime soon
