### ISSUE TITLE
Load function not works for cluster tendrl context object 

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/commons#717]
As per load method implementation in the _copy_vars function, object attributes are passed to the constructor as kwargs. The problem here is parameter name for integration_id in constructor does not match with attribute name in an object so kwargs can't assign a value for that. Also, integration_id is used in render method to form values, Because of this problem integration_id always comes none.

The parameter names should always same as object attributes, then only load will work fine.

**Comment by GowthamShanmugam** [comment]
@r0h4n @shtripat

**Comment by shtripat** [comment]
If that's the case shouldn't we correct the attribute name in class?

**Comment by GowthamShanmugam** [comment]
@shtripat only param is the problem, param should have same which is present in attribute name in class

**Comment by GowthamShanmugam** [comment]
This issue is solved i am closing this issue
