### ISSUE TITLE
Enable ETCD authorization and authentication

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/commons#721]
Tendrl services should use ETCD certificate based auth for any communications with ETCD

https://github.com/coreos/etcd/blob/master/Documentation/authentication.md

Related issue: https://github.com/Tendrl/api/issues/256

**Comment by r0h4n** [comment]
- Etcd User/Password based auth is enabled
- Etcd TLS cert based auth in progress, will be done soon

**Comment by r0h4n** [comment]
Seems like ETCD basicauth (user/password) adds a performance penalty in API responses, we will work to implement TLS cert based auth asap

**Comment by mbukatov** [comment]
@sidhax this seems like security related issue, here we need to figure out how to use etcd cert auth instead of password based auth

**Comment by r0h4n** [comment]
This is fixed

Please check https://github.com/Tendrl/documentation/wiki/Tendrl-with-a-secure-etcd-cluster
