### ISSUE TITLE
Alerts are pushed in etcd when all clearing alerts are removed and directory becomes empty

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/commons#742]
The problem what is found is node-agent will read the alerts from etcd based on alert classification, there are two types of alert classification 1. node 2. cluster. if the alert is node alert then it will read /alerting/nodes/node_id/
if the alert is cluster alerts then it will read /alerting/nodes/cluster_id, this for compare the new incoming alert with existing alert in etcd to find whether the alert in clearing alert or not. So when the alert came then node-agent will read the particular directory and compare all alert.

So the problem is when an alert is healed by ok alert then it will updated in etcd with ttl of 2 days. So when directory goes empty (all ok alerts are removed by TTL) the etcd reading logic goes wrong.

When first most alert came there will be only /alerting/ path only present, so the alert is stored in etcd without any problem. When some alerts came and removed by ttl then the directory is /alerting/nodes/{node_id}/{empty nothing is inside}. so for the second scenario, the alert reading raises an exception. After this, no node alerts are stored in etcd. but cluster alert is stored. when cluster alert directory goes empty then there also this problem will come.
so reading logic have to modify.

Actaul problem is json.load function raise exception when alert object have None value for  tags field.

**Comment by GowthamShanmugam** [comment]
@rishubhjain @shtripat

**Comment by GowthamShanmugam** [comment]
Tendrl/gluster-integration#412

**Comment by r0h4n** [comment]
Is this resolved?

**Comment by GowthamShanmugam** [comment]
@r0h4n it is solved we can close this issue

**Comment by GowthamShanmugam** [comment]
i am closing this issue, it is fixed
