### ISSUE TITLE
Building  tendrl-commons package from master branch is broken

### ISSUE THREAD

**Issue by dahorak** [Tendrl/commons#744]
Building tendrl-commons package from master branch is broken since Sep 28th[1].
Build log shows following *SyntaxError* traceback[2]:
```
Compiling /builddir/build/BUILDROOT/tendrl-commons-1.5.2-20170928T120018.9d3853e.x86_64/usr/lib/python2.7/site-packages/tendrl/commons/__init__.py ...
  File "/usr/lib/python2.7/site-packages/tendrl/commons/__init__.py", line 257
    if etcd_ca_cert_file and str(etcd_ca_cert_file) != "" and etcd_cert_file and str(etcd_cert_file) != ""
                                                                                                         ^
SyntaxError: invalid syntax
```

Which seems to be related to commit 9d3853e5354131c40e595f9baf8ca22f7d4828ec.

[1] https://ci.centos.org/view/tendrl-build-master/job/tendrl-build-1-master-commons/
[2] https://copr-be.cloud.fedoraproject.org/results/tendrl/tendrl/epel-7-x86_64/00609038-tendrl-commons/build.log.gz

**Comment by rishubhjain** [comment]
@dahorak https://ci.centos.org/view/tendrl-build-master/job/tendrl-build-1-master-commons/ The build errors are resolved, Please verify

**Comment by dahorak** [comment]
Works as expected.
