### ISSUE TITLE
NS.tendrl.objects.Job should have attribute updated_at

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/commons#747]
"updated_at" attribute will be used for providing details as to when the Job/Task ends or is last updated.

cc: @gnehapk

**Comment by r0h4n** [comment]
@anivargi Please confirm if the tendrl-api sends out "updated_at" attribute for each Job

**Comment by r0h4n** [comment]
@anivargi Any updates? 

This is blocking @gnehapk

**Comment by anivargi** [comment]
@r0h4n I will verify and update the issue

**Comment by anivargi** [comment]
@r0h4n is the attribute at the top level with `status` or inside the `payload` ?

**Comment by r0h4n** [comment]
`updated_at` is available at the top level with `status`

also, `updated_at` is a generic attribute for all Tendrl objects and will be available for all Tendrl objects

**Comment by anivargi** [comment]
https://github.com/Tendrl/api/pull/309
