### ISSUE TITLE
cluster import failed of import-ready cluster

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/commons#753]
Not long ago installation I've tried to import cluster. It was marked in UI as *ready to import* so there is no reason to not import it. But it failed because of:
```
Failure in Job 8c4a74b6-99d0-48ac-9b51-b61aca1921b0 Flow tendrl.flows.ImportCluster with error: Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 212, in process_job the_flow.run() File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/import_cluster/__init__.py", line 52, in run "import" % integration_id) FlowExecutionFailedError: Cluster with integration_id (106da482-7af3-4ea5-94b0-23698cc5f419) not found, cannot import 
```
After while I've checked data in Etcd:
```
$ etcdctl --endpoints=http://${HOSTNAME}:2379 ls /indexes/tags/tendrl/integration/
/indexes/tags/tendrl/integration/monitoring
/indexes/tags/tendrl/integration/106da482-7af3-4ea5-94b0-23698cc5f419

$ etcdctl --endpoints=http://${HOSTNAME}:2379 get /indexes/tags/tendrl/integration/106da482-7af3-4ea5-94b0-23698cc5f419
["52b41ec0-31c8-4237-b7c7-80afc464a908", "41d50623-4976-4745-ab7a-4a82fd25ea3d", "db70f38a-bc6a-49a1-a0d5-9231dff7d49e", "020e51bb-8109-4ab7-bb0c-6dbd8b8959a3", "d3673282-ddaa-423d-8342-c49aa9d7aa79", "6c1e31f4-68b4-4182-be4d-0bcb3c69c526"
```
So as I understand failed code cluster was not there when I've tried to import it. I think that all required info should be checked to mark cluster as *ready to import* in UI so user can be sure that it is possible to import cluster.

**Comment by r0h4n** [comment]
Please provide steps to reproduce this issue

**Comment by mkudlej** [comment]
1. I've installed cluster by tendrl-ansible from master
2. if installation ended I've correctly shut down all machines (shutdown -h now)
3. after start of all machines again I've tried to import Gluster cluster. Before I've enter import wizard, I've checked if cluster is ready for import

As I've written in description if cluster is marked as ready for import it should be possible to import it without failure mentioned in issue description.

**Comment by r0h4n** [comment]
@shtripat @GowthamShanmugam please triage this issue using steps provided at https://github.com/Tendrl/commons/issues/753#issuecomment-335727142

**Comment by dahorak** [comment]
I'm facing the same issue today multiple times and it might be related with the fact, that I have Gluster cluster with Arbiter volume (created by gdeploy with following config https://github.com/usmqe/usmqe-setup/blob/master/gdeploy_config/volume_beta_arbiter_2_plus_1x2.create.conf).

**Comment by r0h4n** [comment]
@dahorak If you you skip step 2 in comment https://github.com/Tendrl/commons/issues/753#issuecomment-335727142  , do you face the same issue?

**Comment by dahorak** [comment]
@r0h4n yes, there is no reboot in my workflow after the cluster is installed

**Comment by dahorak** [comment]
Ok, si it might not be connected to the volume type (now I was able import cluster with arbiter volume), but maybe some timing issue ... I'll have to confirm... but maybe it fails when the cluster is imported immediately after installation and when it appears in Tendrl web UI.

**Comment by dahorak** [comment]
Not sure if it is related issue, but now the cluster import task failed similarly with slightly different error:
```
Failure in Job 58847f22-db8f-49de-9600-95631a80f4cf Flow tendrl.flows.ImportCluster with error: Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py", line 217, in process_job the_flow.run() File "/usr/lib/python2.7/site-packages/tendrl/commons/flows/import_cluster/__init__.py", line 84, in run raise ex AtomExecutionFailedError: Atom Execution failed. Error: Node doesnt have OS details populated
```
But with this failure, I was able to try to import the cluster again - twice with the same result third time with the error from description of this issue (now the *Import* button is disabled).

**Comment by r0h4n** [comment]
@dahorak

**Comment by r0h4n** [comment]
Please update packages for tendrl-node-agent and tendrl-gluster-integration and try the import again. 

Fixed: https://github.com/Tendrl/node-agent/commit/d43dd0db11204a425f73a3b303c4fb5790be0567
Fixed: https://github.com/Tendrl/commons/commit/6dd5a1ff54824afda701e8e782320c4a8a7166cd
Fixed: https://github.com/Tendrl/gluster-integration/commit/d3ae3a45fac518d435d8a91eee1fbd5072c63aee

**Comment by dahorak** [comment]
I'll rebuild the cluster from scratch and try the scenarios again and let you know.

**Comment by r0h4n** [comment]
Any updates?

**Comment by r0h4n** [comment]
This has been fixed in latest release and snapshot builds. Please re-open if required
