### ISSUE TITLE
Flow "monitoring.flows.NewClusterDashboard" called multiple times

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/commons#755]
`ImportCluster` flow will create multiple jobs to call flow `monitoring.flows.NewClusterDashboard` , These jobs are created by each node being imported in the cluster. I dont think this is required and we can simply invoke the flow `monitoring.flows.NewClusterDashboard` once during import from either of the nodes being imported

**Comment by r0h4n** [comment]
cc @rishubhjain

**Comment by rishubhjain** [comment]
@r0h4n I have a small workaround, In the NewClusterDashbooard flow I can keep a list of cluster_id (integratoin_id) for which dashboards have been already uploaded , and check against the list before uploading new dashboard.

**Comment by r0h4n** [comment]
Flow's  should not contain persistent data. @rishubhjain

**Comment by rishubhjain** [comment]
@r0h4n I can save the details in NS object, or I can save the details in etcd user http://{host}:2379/v2/key/_NS/monitoring/cluster_list

**Comment by r0h4n** [comment]
@rishubhjain We should not call NewClusterDashboard multiple times. Lets fix the ImportCluster flow.

**Comment by shtripat** [comment]
@r0h4n ack. I will think about it and add code.
@nnDarshan if you are there can you check ?
