### ISSUE TITLE
Read configuration details from etcd

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/commons#76]
Common should read configuration details from etcd and able to pass particular configuration details to the modules

**Comment by sankarshanmukhopadhyay** [comment]
Who is assigned to be working on this issue?

**Comment by GowthamShanmugam** [comment]
@sankarshanmukhopadhyay  I am working in this issue, I cant assign my self.

**Comment by GowthamShanmugam** [comment]
Specification: Tendrl/specifications#11

**Comment by r0h4n** [comment]
Any updates on this?

**Comment by GowthamShanmugam** [comment]
@r0h4n i am not started yet

**Comment by GowthamShanmugam** [comment]
this issue is solved so i am closing this
