### ISSUE TITLE
While import cluster we should check the running status of gluster-integration on all the nodes

### ISSUE THREAD

**Issue by shtripat** [Tendrl/commons#775]
Once gluster-integration started from import cluster flow, as a post check we should check running status of gluster-integration and then only mark the import job completed.

**Comment by r0h4n** [comment]
Any updates?

**Comment by shtripat** [comment]
@r0h4n need to work this out. Will take care as a PR.

**Comment by r0h4n** [comment]
Any updates?

**Comment by shtripat** [comment]
There is a check for collectd only.import cluster checks for `is_managed = "yes"` which is actually set by GI. Explicit check for running state of GI is not there yet.
