### ISSUE TITLE
Improve messages for tasks/jobs

### ISSUE THREAD

**Issue by julienlim** [Tendrl/commons#834]
**Problem Description**
- Messages are too verbose
- Task messages (in UI) are several lines and pages long
- Some of the task messages should be Debug (vs. Info), and there ought to be a way to suppress debug vs. non-debug information
- Every config parameter does not need to be expressed in the Task Details as we’re trying to convey what task is performed

**Recommendations**
- Acquiring and releasing of locks should be "debug" tasks
- Filter Task Details table (in UI) to show all rows except “debug” (and add ability to show “debug” or verbose mode)
- For the “Starting configuration of … on <node> with ...” messages (which seems related to the collectd plugin), it may make sense to make all those entries “debug” and have a single line entry (before they kick off) that says “Configuring collectd monitoring on <node>” with an “info” type.

Current Message:
```
Starting configuration of tendrl_gluster on ci-usm3-gl6.usmqe.lab.eng.brq.redhat.com with {"integration_id": "44f8f6f3-a103-437b-a3e1-701db25c5382", "graphite_port": 2003, "logging_socket_path": "/var/run/tendrl/message.sock", "hostname": "ci-usm3-gl6.usmqe.lab.eng.brq.redhat.com", "etcd_ca_cert_file": "/etc/pki/tls/certs/ca-usmqe.crt", "etcd_host": "ci-usm3-server.usmqe.lab.eng.brq.redhat.com", "interval": 60, "node_id": "7c192ea1-429a-4dbe-b70a-61706f1aec78", "graphite_host": "ci-usm3-server.usmqe.lab.eng.brq.redhat.com", "etcd_port": 2379, "interface": "ens3", "etcd_cert_file": "/etc/pki/tls/certs/etcd.crt", "is_provisioner_node": true, "etcd_key_file": "/etc/pki/tls/private/etcd.key"}as conf parameters
```

Recommendation for Message:
```
Configuring <service_name> monitoring on <object>

E.g. Configuring tendrl_gluster on ci-usm3-gl6.usmqe.lab.eng.brq.redhat.com

```

A more comprehensive list of recommendations can be found at [Tendrl Log Messaging Recommendations](https://docs.google.com/document/d/138SFPUlRqdLjISMcd-Cts-vWzY7wfTGWi8GhdQHnh0Q/edit?usp=sharing).

@r0h4n @nthomas-redhat @shtripat @Tendrl/qe @jjkabrown1 @mcarrano @gnehapk @shtripat @a2batic

**Comment by nthomas-redhat** [comment]
@julienlim , Are you working on this? Based on our last conversation you wanted to pick this up

**Comment by julienlim** [comment]
@nthomas-redhat I'm not able to at the moment as I have some other higher priority tasks I have to take care of.  Apologies.

**Comment by r0h4n** [comment]
@nthomas-redhat  any updates on this?
