### ISSUE TITLE
Unmanage Cluster: Task List not fully cleaned up

### ISSUE THREAD

**Issue by julienlim** [Tendrl/commons#839]
In Tendrl 1.6.0, when using the UI, I tried to unmanage a cluster (after an import) multiple times, each time it preserves the task (job ID) information for previous tasks for an unmanaged cluster, but not its task details.

Scenario:
1. Import Cluster
2. Unmanage Cluster
3. Import Cluster
4. Unmanage Cluster
5. Import Cluster

By the time I execute #5, it does not keep the task details for the tasks #1-#4 but I can still see the tasks for #1-#4.  If we're removing task details, then the task ID (or job ID) itself should also be removed.

@r0h4n @shtripat @Tendrl/qe

**Comment by r0h4n** [comment]
Can you attach a screenshot?

**Comment by shtripat** [comment]
IIRC the TTL set for job updates under `/messages/job` is 2 days by default. I feel after two days job updates would be deleted. There is no TTL for completed jobs so in that case the issue might happen. This is the only corner case I can think as reason. @r0h4n ??

**Comment by julienlim** [comment]
<img width="1280" alt="screen shot 2018-02-27 at 9 44 26 am" src="https://user-images.githubusercontent.com/5589919/37044186-d3569fc8-2130-11e8-910a-1a77d2bbbf42.png">

@r0h4n @shtripat Screenshot showing this scenario - this was capturing during the last unmanage cluster attempt.

**Comment by shtripat** [comment]
@r0h4n @nthomas-redhat I feel in this scenario where task details vanish for completed ones and still task remains, we may think of setting a TTL for completed tasks as well as 2 days. What you suggest?

**Comment by r0h4n** [comment]
@shtripat  Yes, you can do that. Also we need watcher on Job.status which will save a copy of this job somewhere in tendrl etcd archive, that way we dont loose the Job

**Comment by shtripat** [comment]
@r0h4n do we enable any such etcd archive at the moment?

**Comment by r0h4n** [comment]
@shtripat  no, it needs to be implemented
