### ISSUE TITLE
Improve log message content

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/commons#843]
Based on suggestions by @julienlim , Improve the log messages, alerts, job update messages across Tendrl repos

https://docs.google.com/document/d/138SFPUlRqdLjISMcd-Cts-vWzY7wfTGWi8GhdQHnh0Q/edit

**Comment by r0h4n** [comment]
Duplicate of : https://github.com/Tendrl/commons/issues/834

**Comment by julienlim** [comment]
Updating as observed some inconsistency in the Event messages -- see https://bugzilla.redhat.com/show_bug.cgi?id=1597876.

@r0h4n
