### ISSUE TITLE
Enhance unit tests for better coverage

### ISSUE THREAD

**Issue by shtripat** [Tendrl/commons#85]
As part of re-factoring, the unit test coverage is decreased. More unit tests should be written for better coverage.

**Comment by r0h4n** [comment]
@rishubhjain Please start with unit tests for this repo.

Id prefer you tackle below first
- https://github.com/Tendrl/commons/blob/develop/tendrl/commons/__init__.py

**Comment by rishubhjain** [comment]
@r0h4n  as per our discussion if possible could you provide me some time period for the task.

**Comment by r0h4n** [comment]
@rishubhjain Lets check the task progress every alternate day.

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/commons/pull/559
