### ISSUE TITLE
Even the expand cluster job failed, the current_job property shows it in_progress state

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/commons#869]
`"current_job":"{\"status\": \"in_progress\", \"job_id\": \"b7eccd0f-50f9-43d2-83ba-b5c831871941\", \"job_name\": \"ExpandClusterWithDetectedPeers\"}",
`

Steps-
1) Fire expand flow 
2) Job failed because of timeout
3) Go to cluster list page and check `/clusters` response

**Comment by shirshendu** [comment]
@gnehapk See discussion here: https://github.com/Tendrl/api/pull/386 https://github.com/Tendrl/commons/issues/866

**Comment by GowthamShanmugam** [comment]
@shtripat

**Comment by shtripat** [comment]
So if a job is timed out due to not being picked at all, we actually don't have any control. Yes in case of expand cluster flow, in case time out we need to set the current job status properly. Will send a PR for the same.

**Comment by r0h4n** [comment]
This is fixed, please verify @gnehapk
