### ISSUE TITLE
Etcd read and writes are affected due to race condition from multiple threads

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/commons#885]
As we discussed in the daily call we have to introduce a job framework to do read and write from the central store.

**Comment by GowthamShanmugam** [comment]
@shirshendu @shtripat @r0h4n @nthomas-redhat anyone please explain here like  the how to we handle this problem

**Comment by shirshendu** [comment]
Let's start with documenting all known scenarios here, with the following details:
- when race condition is happening (scenario)
- which two parts of the code the race is between (or is it between two instances of the same part)
- which part of the data is impacted (for ex: cluster data, volume data etc)

At this point, we can evaluate if the race condition is something that would benefit from leveraging our job framework, or if its solution lies elsewhere.

If we decide on using our job framework :-
For these affected objects, we need to ensure that their attributes are _written_ to etcd only by a job.
We possibly also need to ensure that any job wanting to update an object is only queued if there are no other write jobs for that object.

**Comment by r0h4n** [comment]
https://github.com/Tendrl/commons/issues/889
