### ISSUE TITLE
Improving etcd performance

### ISSUE THREAD

**Issue by shirshendu** [Tendrl/commons#889]
Right now, we store objects in etcd with attributes exploded, and then every interaction with these objects leads to multiple reads/writes as per the number of attributes on each objects. 
We have two approaches to investigate:
- Completely outside of code, add etcds on node-agents as peers, and allow data sync across an etcd cluster, i.e. scale etcd
- We can store object data as marshalled JSON/YAML -- similar to gd2, will need code, as well as extra effort in migration of schema as well

Any change in this respect would have a fairly wide impact, so we may or may not want it in the current release.

**Comment by r0h4n** [comment]
About
- Completely outside of code, add etcds on node-agents as peers, and allow data sync across an etcd cluster, i.e. scale etcd

This topic requires more wider discussions, lets not target this for immediate release.

About
- We can store object data as marshalled JSON/YAML -- similar to gd2, will need code, as well as extra effort in migration of schema as well

We should target that for immediate release
