### ISSUE TITLE
duplication of example configuration files

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/commons#89]
I noticed that most of example/default config files in tendrl-common are present in all other python tendrl projects.

This state has additional maintenance cost and it's error prone when changes needs to be introduced in those files. In other words, it is be hard to maintain in the long term.

## Related Work/Issues

The root cause of this is the same as in few other already reported issues:

* https://github.com/Tendrl/node_agent/issues/99
* https://github.com/Tendrl/ceph_integration/issues/57
* https://github.com/Tendrl/gluster_integration/issues/86

This particular issue is created so that we consider this side of the problem as well during redesign of Tendrl configuration.

## Details

There are these example config files in tendrl-common:

```
$ find common/etc/ -type f
common/etc/tendrl/tendrl.conf.sample
common/etc/samples/logging.yaml.syslog.sample
common/etc/samples/tendrl_definitions_generic-0.3.sample.yaml
common/etc/samples/tendrl_api_job.sample.json
common/etc/samples/logging.yaml.timedrotation.sample
common/etc/samples/logging.yaml.journald.sample
```

And 4 of them (out of 6) are present in all other python tendlr components:

* tendrl.conf.sample
* logging.yaml.journald.sample
* logging.yaml.timedrotation.sample
* logging.yaml.syslog.sample

Changes in each components look like this:

```
$ diff common/etc/tendrl/tendrl.conf.sample node_agent/etc/tendrl/tendrl.conf.sample 
10d9
< log_level = DEBUG
11a11,22
> log_level = DEBUG
> 
> 
> [node_agent]
> # Path to log file
> log_level = DEBUG
> tendrl_exe_file_prefix = /tmp/.tendrl_runner
> log_cfg_path = /etc/tendrl/node_agent_logging.yaml
> 
> # installation_source_type decides how tendrl will install a software
> # the possible values are pip, rpm, deb.
> installation_source_type = rpm
```

```
$ diff common/etc/tendrl/tendrl.conf.sample ceph_bridge/etc/tendrl/tendrl.conf.sample 
10d9
< log_level = DEBUG
11a11,23
> log_level = DEBUG
> 
> 
> [ceph_integration]
> # Path to log file
> log_cfg_path = /etc/tendrl/logging.yaml
> log_level = DEBUG
> crush_host_type = host
> crush_osd_type = osd
> favorite_timeout_factor = 3
> server_timeout_factor = 3
> cluster_contact_threshold = 60
> cluster_map_retention = 3600
```

**Comment by mbukatov** [comment]
I wrote very simple script to recheck this: https://gist.github.com/mbukatov/99677776d905af50e265b69490484d8e

**Comment by mbukatov** [comment]
Progress has been made there, current master branch (commit e4a8559) no longer contains `etc` directory.

**Comment by mbukatov** [comment]
On the other hand, I see these 3 files duplicated in all other python tendrl components:

```
logging.yaml.journald.sample
logging.yaml.syslog.sample
logging.yaml.timedrotation.sample
```

And while those files are medium sized with lots of configuration:

```
$ find -name logging.yaml.journald.sample | xargs wc -l
  38 ./tendrl-ceph-integration/etc/tendrl/ceph-integration/logging.yaml.journald.sample
  38 ./tendrl-gluster-integration/etc/tendrl/gluster-integration/logging.yaml.journald.sample
  38 ./tendrl-performance-monitoring/node_monitoring/etc/tendrl/node-monitoring/logging.yaml.journald.sample
  38 ./tendrl-performance-monitoring/etc/tendrl/performance-monitoring/logging.yaml.journald.sample
  38 ./tendrl-node-agent/etc/tendrl/node-agent/logging.yaml.journald.sample
  38 ./tendrl-alerting/etc/logging.yaml.journald.sample
 228 total
```

The differences among particular components are rather small:

```
$ diff 'tendrl-alerting/etc/logging.yaml.journald.sample' 'tendrl-node-agent/etc/tendrl/node-agent/logging.yaml.journald.sample'
19c19
<         filename: /var/log/tendrl/alerting/alerting_info.log
---
>         filename: /var/log/tendrl/node-agent/node-agent_info.log
25c25
<         filename: /var/log/tendrl/alerting/alerting_errors.log
---
>         filename: /var/log/tendrl/node-agent/node-agent_errors.log
```

**Comment by mbukatov** [comment]
This issue may be related: https://github.com/Tendrl/commons/issues/60

While I agree that code of tendrl-commons library should not read from hard coded configuration files itself, it may make sense to have common defaults in tendrl-commons so that other components doesn't have to duplicate 90% default configuration values.

**Comment by r0h4n** [comment]
I am not with having configuration files in commons, commons can consume the Config objects from NS.config (Config objects are supplied and controlled by namespaces "node_agent", "tendrl.ceph", "tendrl.gluster", performance_monitoring, node_monitoring, alerting

**Comment by mbukatov** [comment]
Point raised in https://github.com/Tendrl/commons/issues/89#issuecomment-283670537 is still valid today - the duplication across repositories/components still exists: 

```
$ diff tendrl-ceph-integration/etc/tendrl/ceph-integration/logging.yaml.journald.sample tendrl-gluster-integration/etc/tendrl/gluster-integration/logging.yaml.journald.sample 
19c19
<         filename: /var/log/tendrl/ceph-integration/ceph-integration_info.log
---
>         filename: /var/log/tendrl/gluster-integration/gluster-integration_info.log
25c25
<         filename: /var/log/tendrl/ceph-integration/ceph-integration_errors.log
---
>         filename: /var/log/tendrl/gluster-integration/gluster-integration_errors.log
```

This issue has been closed (in a won't fix sense) by rohan - see https://github.com/Tendrl/commons/issues/89#issuecomment-286866301
