### ISSUE TITLE
If no. of volumes is more there are `Raft internal Error` while talking to etcd

### ISSUE THREAD

**Issue by shtripat** [Tendrl/commons#919]
If we keep running the setup for sometime and no of volumes is more (>4) we see `raft internal error` while connecting to etcd.

**Comment by mbukatov** [comment]
Could full error be posted here?

**Comment by shtripat** [comment]
So a sample error which tendrl modules see once these starts happening looks something like 

```
Raft Internal Error : etcdserver: request timed out - EtcdException:
```

For a 2 node gluster cluster managed by tendrl server (which ran into Raft error within ~30 mins), we tried few tunables in etcd as below but to no help (it again ran into raft error with ~20mins)

```
ETCD_MAX_SNAPSHOTS="1"
ETCD_SNAPSHOT_COUNT="1000"
```

Post this for the same cluster we have enabled below configurations and cluster is up and running without a raft error for more than a hour now. Will need a further and longer review on the setup.

```
ETCD_HEARTBEAT_INTERVAL="10000"
ETCD_ELECTION_TIMEOUT="50000"
```

**Comment by r0h4n** [comment]
@shtripat any updates?

**Comment by shtripat** [comment]
After setting the below tunables, the issue is not seen off late. Closing the issue for the time being and if something crops up we will have look for tunable values etc.

```
ETCD_MAX_SNAPSHOTS="2"
ETCD_SNAPSHOT_COUNT="5000"
ETCD_HEARTBEAT_INTERVAL="10000"
ETCD_ELECTION_TIMEOUT="50000"
```
