### ISSUE TITLE
Debug messages are added to the task details 

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/commons#934]
No debug messages should be looged as part of the task details

Import cluster:
debug Link /var/lib/carbon/whisper/tendrl/names/ea3d62cc-8f76-47a8-bf78-5a490340df58 -> /var/lib/carbon/whisper/tendrl//clusters/ea3d62cc-8f76-47a8-bf78-5a490340df58 created

Unamange Cluster:
debug /alerting/nodes/ffbdbfb4-ef18-4317-b65f-40b4783d88b7 key not found for deletion 24 Apr 2018 09:03:06
debug /alerting/clusters/ea3d62cc-8f76-47a8-bf78-5a490340df58 key not found for deletion 24 Apr 2018 09:03:06
debug /alerting/nodes/af2f6351-dc5a-4f15-90d4-7fb2247641e4 key not found for deletion 24 Apr 2018 09:03:06
debug /alerting/nodes/f52ef68c-7478-4e98-bb1f-7e40fceb8734 key not found for deletion 24 Apr 2018 09:03:06
debug /clusters/ea3d62cc-8f76-47a8-bf78-5a490340df58/raw_map key not found for deletion 24 Apr 2018 09:03:06

**Comment by GowthamShanmugam** [comment]
This issue is fixed
